#! /bin/sh -e

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"
cd "$ROOT"

SUBJ="/C=CN/ST=Shanghai/L=Shanghai/O=LikeIT"

if [ $# -ne 2 ]; then
    echo "Usage: $0 {identify} {Common Name}"
    echo "e.g. $0 api.paadoo.net 'api.paadoo.net'"
    exit 1
else
    NAME=$1
    SUBJ="$SUBJ/CN=$2"
fi

INTERMEDIATECA="$(sed -rn 's;^ *_CANAME_ *= *(.+)$;\1;p' openssl.cnf)"
if [ -z "$INTERMEDIATECA" ]; then
    echo "ERROR: _CANAME_ not given in openssl.cnf file"
    exit 1
fi
if [ ! -f "../intermediate/certs/$INTERMEDIATECA.crt" -o ! -f "../intermediate/certs/$INTERMEDIATECA.key" ]; then
    echo "ERROR: IntermediateCA not found, you must generate intermediateCA first"
    exit 1
fi

./init

# RSA
#openssl genrsa -out "certs/$NAME.key" 2048
# ECDSA
openssl ecparam -out "certs/$NAME.key" -name prime256v1 -genkey
openssl req -new -key "certs/$NAME.key" -out "certs/$NAME.csr" -subj "$SUBJ"
openssl ca -batch -config openssl.cnf -notext -in "certs/$NAME.csr" -out "certs/$NAME.crt"

openssl ca -config openssl.cnf -gencrl | openssl crl -inform PEM -outform DER -out "$INTERMEDIATECA.crl"

#exit
PASS="$(openssl rand -base64 32)"
openssl ec -aes-256-cbc -passout "pass:$PASS" -in "certs/$NAME.key" -out "certs/$NAME.key"
echo
echo "WARNING!!! 请妥善保管好 $NAME 的私钥保护密码"
echo
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo "PASSWORD = $PASS"
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo
